# Configurations used when running emmocheck from the ci_emmocheck workflow

skip:
  - test_description

test_number_of_labels:
  exceptions:
    - ssbd.Software
    - ssbd.Computation
    - ssbd.Information
    - ssbd.Model
    
