# Configurations used when running emmocheck from the ci_emmocheck workflow

skip:
  - test_description

enable:
  - test_number_of_rdfslabels

test_number_of_labels:
  exceptions:
    - ssbd.Software
    - ssbd.Information
    - ssbd.Model
 
test_number_of_rdfslabels:
  exceptions:
    - ssbd.Software
    - ssbd.Information
    - ssbd.Model
    
