ONTOLOGY_NAME: core
ONTOLOGY_PREFIX: ssbd
ONTOLOGY_IRI: https://w3id.org/ssbd
GITHUB_REPOSITORY: ssbd-ontology/core
BUILD_DIR: build

# Optional: select subsections for the primary reference index.
# Default is "all".
# REFERENCE_SUBSECTIONS: all
# Example subset:
# REFERENCE_SUBSECTIONS: classes,annotation_properties,data_properties,object_properties,individuals
#
# Optional: additional reference indices for `ontokit docs`.
REFERENCE_INDICES:
  - ontology_file: build/core-squashed.ttl
    title: Properties Index
    docfile: properties.rst
    # iri_regex: https://example.org/other
    imported: false
    recursive: false
    subsections: annotation_properties,object_properties,data_properties
